const cards = [
  ['Main page', 'Fairytales', 'Animals (set A)', 'Animals (set B)', 'Animals (set C)', 'Food (set A)', 'Food (set B)', 'Profession', 'Places'],
  [
    {
      word: 'Fairytales',
      image: 'img/mainPage/fairytales.jpg',
    },
    {
      word: 'Animals (set A)',
      image: 'img/mainPage/animalsA.jpg',
    },
    {
      word: 'Animals (set B)',
      image: 'img/mainPage/animalsB.jpg',
    },
    {
      word: 'Animals (set C)',
      image: 'img/mainPage/animalsC.jpg',
    },
    {
      word: 'Food (set A)',
      image: 'img/mainPage/foodA.jpg',
    },
    {
      word: 'Food (set B)',
      image: 'img/mainPage/foodB.jpg',
    },
    {
      word: 'Profession',
      image: 'img/mainPage/profession.jpg',
    },
    {
      word: 'Places',
      image: 'img/mainPage/places.jpg',
    },
  ],
  [
    {
      word: 'Dragon',
      translation: 'Дракон',
      image: 'img/fairytales/dragon.svg',
      audioSrc: 'audio/dragon.mp3',
    },
    {
      word: 'Unicorn',
      translation: 'Единорог',
      image: 'img/fairytales/unicorn.svg',
      audioSrc: 'audio/unicorn.mp3',
    },
    {
      word: 'Ghost',
      translation: 'Призрак',
      image: 'img/fairytales/ghost.svg',
      audioSrc: 'audio/ghost.mp3',
    },
    {
      word: 'King',
      translation: 'Король',
      image: 'img/fairytales/king.svg',
      audioSrc: 'audio/king.mp3',
    },
    {
      word: 'Princess',
      translation: 'Принцесса',
      image: 'img/fairytales/princess.svg',
      audioSrc: 'audio/princess.mp3',
    },
    {
      word: 'Mermaid',
      translation: 'Русалка',
      image: 'img/fairytales/mermaid.svg',
      audioSrc: 'audio/mermaid.mp3',
    },
    {
      word: 'Wizard',
      translation: 'Волшебник',
      image: 'img/fairytales/wizard.svg',
      audioSrc: 'audio/wizard.mp3',
    },
    {
      word: 'Fairy',
      translation: 'Фея',
      image: 'img/fairytales/fairy.svg',
      audioSrc: 'audio/fairy.mp3',
    },
  ],
  [
    {
      word: 'Cat',
      translation: 'Кот',
      image: 'img/animals/cat.svg',
      audioSrc: 'audio/cat.mp3',
    },
    {
      word: 'Beaver',
      translation: 'Бобер',
      image: 'img/animals/beaver.svg',
      audioSrc: 'audio/beaver.mp3',
    },
    {
      word: 'Cow',
      translation: 'Корова',
      image: 'img/animals/cow.svg',
      audioSrc: 'audio/cow.mp3',
    },
    {
      word: 'Dog',
      translation: 'Собака',
      image: 'img/animals/dog.svg',
      audioSrc: 'audio/dog.mp3',
    },
    {
      word: 'Donkey',
      translation: 'Осел',
      image: 'img/animals/donkey.svg',
      audioSrc: 'audio/donkey.mp3',
    },
    {
      word: 'Frog',
      translation: 'Лягушка',
      image: 'img/animals/frog.svg',
      audioSrc: 'audio/frog.mp3',
    },
    {
      word: 'Hamster',
      translation: 'Хомяк',
      image: 'img/animals/hamster.svg',
      audioSrc: 'audio/hamster.mp3',
    },
    {
      word: 'Horse',
      translation: 'Лошадь',
      image: 'img/animals/horse.svg',
      audioSrc: 'audio/horse.mp3',
    },
  ],
  [
    {
      word: 'Jellyfish',
      translation: 'Медуза',
      image: 'img/animals/jellyfish.svg',
      audioSrc: 'audio/jellyfish.mp3',
    },
    {
      word: 'Kangaroo',
      translation: 'Кенгуру',
      image: 'img/animals/kangaroo.svg',
      audioSrc: 'audio/kangaroo.mp3',
    },
    {
      word: 'Elephant',
      translation: 'Слон',
      image: 'img/animals/elephant.svg',
      audioSrc: 'audio/elephant.mp3',
    },
    {
      word: 'Lion',
      translation: 'Лев',
      image: 'img/animals/lion.svg',
      audioSrc: 'audio/lion.mp3',
    },
    {
      word: 'Mouse',
      translation: 'Мышка',
      image: 'img/animals/mouse.svg',
      audioSrc: 'audio/mouse.mp3',
    },
    {
      word: 'Sheep',
      translation: 'Овца',
      image: 'img/animals/sheep.svg',
      audioSrc: 'audio/sheep.mp3',
    },
    {
      word: 'Raccoon',
      translation: 'Муравьед',
      image: 'img/animals/raccoon.svg',
      audioSrc: 'audio/raccoon.mp3',
    },
    {
      word: 'Turtle',
      translation: 'Черепаха',
      image: 'img/animals/turtle.svg',
      audioSrc: 'audio/turtle.mp3',
    },
  ],
  [
    {
      word: 'Panda',
      translation: 'Панда',
      image: 'img/animals/panda.svg',
      audioSrc: 'audio/panda.mp3',
    },
    {
      word: 'Octopus',
      translation: 'Осьминог',
      image: 'img/animals/octopus.svg',
      audioSrc: 'audio/octopus.mp3',
    },
    {
      word: 'Snake',
      translation: 'Змея',
      image: 'img/animals/snake.svg',
      audioSrc: 'audio/snake.mp3',
    },
    {
      word: 'Whale',
      translation: 'Кит',
      image: 'img/animals/whale.svg',
      audioSrc: 'audio/whale.mp3',
    },
    {
      word: 'Yak',
      translation: 'Як',
      image: 'img/animals/yak.svg',
      audioSrc: 'audio/yak.mp3',
    },
    {
      word: 'Fish',
      translation: 'Рыба',
      image: 'img/animals/fish.svg',
      audioSrc: 'audio/fish.mp3',
    },
    {
      word: 'Zebra',
      translation: 'Зебра',
      image: 'img/animals/zebra.svg',
      audioSrc: 'audio/zebra.mp3',
    },
    {
      word: 'Сrocodile',
      translation: 'Крокодил',
      image: 'img/animals/crocodile.svg',
      audioSrc: 'audio/crocodile.mp3',
    },
  ],
  [
    {
      word: 'Beetroot ',
      translation: 'Свекла',
      image: 'img/food/beetroot.svg',
      audioSrc: 'audio/beetroot.mp3',
    },
    {
      word: 'Cabbage ',
      translation: 'Капуста',
      image: 'img/food/cabbage.svg',
      audioSrc: 'audio/cabbage.mp3',
    },
    {
      word: 'Cake',
      translation: 'Торт',
      image: 'img/food/cake.svg',
      audioSrc: 'audio/cake.mp3',
    },
    {
      word: 'Cucumber',
      translation: 'Огурец',
      image: 'img/food/cucumber.svg',
      audioSrc: 'audio/cucumber.mp3',
    },
    {
      word: 'Meat',
      translation: 'Мясо',
      image: 'img/food/meat.svg',
      audioSrc: 'audio/meat.mp3',
    },
    {
      word: 'Pizza',
      translation: 'Пицца',
      image: 'img/food/pizza.svg',
      audioSrc: 'audio/pizza.mp3',
    },
    {
      word: 'Sandwich',
      translation: 'Бутерброд',
      image: 'img/food/sandwich.svg',
      audioSrc: 'audio/sandwich.mp3',
    },
    {
      word: 'Tomato',
      translation: 'Помидор',
      image: 'img/food/tomato.svg',
      audioSrc: 'audio/tomato.mp3',
    },
  ],
  [
    {
      word: 'Egg',
      translation: 'Яйцо',
      image: 'img/food/egg.svg',
      audioSrc: 'audio/egg.mp3',
    },
    {
      word: 'Bread',
      translation: 'Хлеб',
      image: 'img/food/bread.svg',
      audioSrc: 'audio/bread.mp3',
    },
    {
      word: 'Banana',
      translation: 'Банан',
      image: 'img/food/banana.svg',
      audioSrc: 'audio/banana.mp3',
    },
    {
      word: 'Bacon',
      translation: 'Бекон',
      image: 'img/food/bacon.svg',
      audioSrc: 'audio/bacon.mp3',
    },
    {
      word: 'Сheese',
      translation: 'Сыр',
      image: 'img/food/cheese.svg',
      audioSrc: 'audio/cheese.mp3',
    },
    {
      word: 'Milk',
      translation: 'Молоко',
      image: 'img/food/milk.svg',
      audioSrc: 'audio/milk.mp3',
    },
    {
      word: 'Ice Cream',
      translation: 'Мороженое',
      image: 'img/food/iceCream.svg',
      audioSrc: 'audio/iceCream.mp3',
    },
    {
      word: 'Sausage',
      translation: 'Колбаса',
      image: 'img/food/sausage.svg',
      audioSrc: 'audio/sausage.mp3',
    },
  ],
  [
    {
      word: 'Cook',
      translation: 'Повар',
      image: 'img/profession/cook.svg',
      audioSrc: 'audio/cook.mp3',
    },
    {
      word: 'Doctor',
      translation: 'Доктор',
      image: 'img/profession/doctor.svg',
      audioSrc: 'audio/doctor.mp3',
    },
    {
      word: 'Scientist',
      translation: 'Ученый',
      image: 'img/profession/scientist.svg',
      audioSrc: 'audio/scientist.mp3',
    },
    {
      word: 'Painter',
      translation: 'Художник',
      image: 'img/profession/painter.svg',
      audioSrc: 'audio/painter.mp3',
    },
    {
      word: 'Policeman',
      translation: 'Полицейский',
      image: 'img/profession/policeman.svg',
      audioSrc: 'audio/policeman.mp3',
    },
    {
      word: 'Lifeguard',
      translation: 'Спасатель',
      image: 'img/profession/lifeguard.svg',
      audioSrc: 'audio/lifeguard.mp3',
    },
    {
      word: 'Teacher',
      translation: 'Учитель',
      image: 'img/profession/teacher.svg',
      audioSrc: 'audio/teacher.mp3',
    },
    {
      word: 'Solicitor',
      translation: 'Адвокат',
      image: 'img/profession/solicitor.svg',
      audioSrc: 'audio/solicitor.mp3',
    },
  ],
  [
    {
      word: 'Bitch',
      translation: 'Пляж',
      image: 'img/places/bitch.svg',
      audioSrc: 'audio/bitch.mp3',
    },
    {
      word: 'City',
      translation: 'Город',
      image: 'img/places/city.svg',
      audioSrc: 'audio/city.mp3',
    },
    {
      word: 'Desert',
      translation: 'Пустыня',
      image: 'img/places/desert.svg',
      audioSrc: 'audio/desert.mp3',
    },
    {
      word: 'Field',
      translation: 'Поле',
      image: 'img/places/field.svg',
      audioSrc: 'audio/field.mp3',
    },
    {
      word: 'Forest',
      translation: 'Лес',
      image: 'img/places/forest.svg',
      audioSrc: 'audio/forest.mp3',
    },
    {
      word: 'River',
      translation: 'Река',
      image: 'img/places/river.svg',
      audioSrc: 'audio/river.mp3',
    },
    {
      word: 'Room',
      translation: 'Комната',
      image: 'img/places/room.svg',
      audioSrc: 'audio/room.mp3',
    },
    {
      word: 'Village',
      translation: 'Деревня',
      image: 'img/places/village.svg',
      audioSrc: 'audio/village.mp3',
    },
  ],
];

export default cards;
